services:

  database:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: scrap_db
    volumes:
      - postgres-db:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    ports:
      - 8000:8000
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    depends_on:
      - backend

volumes:
  postgres-db:
    driver: local

